server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
  instance:
    preferIpAddress: true

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        routes:

#          - id: first
#            uri: lb://first
#            predicates:
#              - Path=/first/**
#
#
#          - id: second
#            uri: lb://second
#            predicates:
#              - Path=/second/**



          - id: first
            predicates:
              - name: Path
                args:
                  regex: /first/**
            uri: lb://first

          - id: second
            predicates:
              - name: Path
                args:
                  regex: /second/**
            uri: lb://second



  management:
    tracing:
      sampling:
        probability: 1.0


#          - id: students
#              uri: http://localhost:8090
#              predicates:
#                - Path=/api/v1/students/**
#
#          - id: schools
#              uri: http://localhost:8070
#              predicates:
#                - Path=/api/v1/schools/**


